// Hand-classified topic mapping for Cory's book collection
// Keys are _filename values, values are arrays of topics

export const topicMap: Record<string, string[]> = {
  'A Brief History of Intelligence': ['Science', 'Psychology'],
  'A Higher Loyalty': ['Politics', 'Memoir'],
  'A Mind at Play': ['Biography', 'Science', 'Technology'],
  'A Pattern Language': ['Design', 'Philosophy'],
  'A Pattern Language (Hoopla)': ['Design', 'Philosophy'],
  'A Promised Land': ['Politics', 'Memoir'],
  'A Woman of No Importance': ['History', 'Military', 'Biography'],
  'Abundance': ['Economics', 'Politics'],
  'Accelerando': ['Fiction', 'Technology'],
  'Alexander Hamilton': ['Biography', 'History', 'Politics'],
  'All Systems Red': ['Fiction', 'Technology'],
  'Altered Carbon': ['Fiction', 'Technology'],
  'American Moonshot': ['History', 'Space', 'Politics'],
  'American Prometheus': ['Biography', 'Science', 'History'],
  'Andrew Carnegie': ['Biography', 'Business', 'History'],
  'Apollo': ['History', 'Space', 'Technology'],
  'Apollo (Hoopla)': ['History', 'Space', 'Technology'],
  'Because Internet': ['Linguistics', 'Technology', 'Social Science'],
  'Becoming Trader Joe': ['Business', 'Memoir'],
  'Becoming': ['Memoir', 'Politics'],
  'Behemoth': ['History', 'Economics', 'Business'],
  'Benjamin Franklin': ['Biography', 'History'],
  'Benjamin Franklin (Hoopla)': ['Biography', 'History'],
  'Black Edge': ['Business', 'Economics'],
  'Bobos in Paradise': ['Social Science', 'Economics'],
  'Bowling Alone': ['Social Science', 'Politics'],
  'Brave New World': ['Fiction'],
  'Build': ['Business', 'Technology', 'Design'],
  'Caste': ['Social Science', 'History'],
  "Cat's Cradle": ['Fiction', 'Science'],
  'Chaos': ['Science'],
  'Chip War': ['Technology', 'History', 'Economics'],
  'Churchill': ['Biography', 'History', 'Military'],
  'Coming Apart': ['Social Science', 'Politics'],
  'Content': ['Technology', 'Economics'],
  'Creative Selection': ['Technology', 'Business', 'Design'],
  'Cribsheet': ['Parenting', 'Science'],
  'Cryptonomicon': ['Fiction', 'Technology'],
  'Daydream Believers': ['Politics', 'History'],
  'Decline and Fall of the Roman Empire, Part I': ['History'],
  'Digital Apollo': ['Technology', 'Space', 'History'],
  'Dinners with Ruth': ['Memoir', 'Politics'],
  'Dominion': ['History'],
  "Don't Sleep, There Are Snakes": ['Linguistics', 'Science'],
  'East of Eden': ['Fiction'],
  'Edison': ['Biography', 'Technology', 'History'],
  'Einstein': ['Biography', 'Science'],
  'Elon Musk': ['Biography', 'Technology', 'Business'],
  'Endurance': ['History', 'Biography'],
  'Every Living Thing': ['Science', 'History'],
  'Expecting Better': ['Parenting', 'Science'],
  'Fahrenheit 451': ['Fiction'],
  'Fair Play': ['Parenting', 'Social Science'],
  'Fascism': ['Politics', 'History'],
  'Fear': ['Politics'],
  'Game On!': ['Technology', 'History'],
  'Geniuses at War': ['History', 'Military', 'Science'],
  'Hard Choices': ['Politics', 'Memoir'],
  'Healing Back Pain': ['Health'],
  'Healing Back Pain (copy)': ['Health'],
  'How Google Works': ['Business', 'Technology'],
  'How Not to Be Wrong': ['Science'],
  'How to Build a Car': ['Biography', 'Design', 'Technology'],
  'How to Keep House While Drowning': ['Health', 'Psychology'],
  "I'll Take Your Questions Now": ['Politics', 'Memoir'],
  'Ignition!': ['Science', 'Space', 'History'],
  'Into the Wild': ['Biography', 'Memoir'],
  'Invisible Women': ['Social Science'],
  'John Adams': ['Biography', 'History', 'Politics'],
  'Kelly': ['Biography', 'Technology', 'Military'],
  'Kitchen Confidential': ['Memoir', 'Food'],
  'Landslide': ['Politics'],
  'Leonardo da Vinci': ['Biography', 'Science', 'Design'],
  'Liftoff': ['Space', 'Business', 'Technology'],
  'Machines of Loving Grace': ['Technology', 'History'],
  "Madame Fourcade's Secret War": ['History', 'Military', 'Biography'],
  'Master of the Senate': ['Biography', 'Politics', 'History'],
  'Of Mice and Men': ['Fiction'],
  'Of Thee I Sing': ['Politics'],
  'Our Robots, Ourselves': ['Technology', 'Science'],
  'Peril': ['Politics'],
  'Precious Little Sleep': ['Parenting'],
  'Profiles in Courage': ['Politics', 'History', 'Biography'],
  'Proyecto Hail Mary': ['Fiction', 'Science', 'Space'],
  'Raising Steam': ['Fiction'],
  'Ready Player One': ['Fiction', 'Technology'],
  'Ready Player Two': ['Fiction', 'Technology'],
  'Reconstruction': ['History', 'Politics'],
  'Salmon': ['Food', 'History'],
  'Salt': ['Food', 'History'],
  'Shoe Dog': ['Business', 'Memoir', 'Biography'],
  'Shop Class as Soulcraft': ['Philosophy', 'Social Science'],
  'Sisters in Law': ['Politics', 'History', 'Biography'],
  'Skunk Works': ['Technology', 'Military', 'Biography'],
  'Slow Down': ['Economics', 'Philosophy'],
  'Southern Lady Code': ['Fiction', 'Memoir'],
  'Spare': ['Memoir'],
  'Stiff': ['Science'],
  'Stuff Matters': ['Science', 'Design'],
  'Surfaces and Essences': ['Philosophy', 'Science', 'Linguistics'],
  'Surprise, Kill, Vanish': ['Military', 'History'],
  'Terry Pratchett': ['Fiction'],
  'The 9-11 Commission Report': ['Politics', 'History'],
  'The Age of Wonder': ['Science', 'History'],
  'The Alchemist': ['Fiction', 'Philosophy'],
  'The Anxious Generation': ['Psychology', 'Social Science', 'Parenting'],
  'The Astronaut Wives Club': ['Space', 'History'],
  'The Box': ['History', 'Economics', 'Business'],
  'The Chief': ['Biography', 'Politics'],
  'The Club': ['History', 'Social Science'],
  'The Code Breaker': ['Biography', 'Science', 'Technology'],
  'The Creative Act': ['Philosophy', 'Design'],
  'The Design of Everyday Things': ['Design', 'Psychology'],
  'The Diary of Anne Frank': ['History'],
  'The Diary of a Young Girl': ['History', 'Memoir'],
  'The Disappearing Spoon': ['Science'],
  'The Extended Mind': ['Psychology', 'Science'],
  'The Generals': ['Military', 'History'],
  'The Girls Who Stepped Out of Line': ['History', 'Military', 'Biography'],
  'The Grapes of Wrath': ['Fiction'],
  'The Guns of August': ['History', 'Military'],
  'The Gunslinger': ['Fiction'],
  'The Halloween Tree': ['Fiction'],
  'The Hard Thing About Hard Things': ['Business'],
  'The Idea Factory': ['Technology', 'History', 'Business'],
  'The Information': ['Science', 'Technology', 'History'],
  'The Invention of Science': ['Science', 'History'],
  'The Last Lion': ['Biography', 'History', 'Military'],
  'The MANIAC': ['Fiction', 'Science', 'History'],
  'The Making of a Justice': ['Memoir', 'Politics'],
  'The Ministry of Ungentlemanly Warfare': ['History', 'Military'],
  'The One Device': ['Technology', 'Business', 'History'],
  'The Operator': ['Military', 'Memoir'],
  'The Organization Man': ['Social Science', 'Business'],
  'The Origins of Efficiency': ['History', 'Economics'],
  'The Path to Power': ['Biography', 'Politics', 'History'],
  'The Perfectionists': ['History', 'Technology', 'Science'],
  'The Power Broker, Volume 1 of 3': ['Biography', 'Politics', 'History'],
  'The Race Underground': ['History', 'Technology'],
  'The Rise and Fall of the Third Reich': ['History', 'Military'],
  'The Rise of the G.I. Army, 1940-1941': ['History', 'Military'],
  'The Scaling Era': ['Technology'],
  'The Score Takes Care of Itself': ['Business'],
  'The Secret History': ['Fiction'],
  'The Secret Horsepower Race': ['History', 'Military', 'Technology'],
  'The Splendid and the Vile': ['History', 'Biography', 'Military'],
  'The Story of Art Without Men': ['History', 'Social Science'],
  'The Things We Make': ['Technology', 'Design', 'Philosophy'],
  'The Third Reich at War': ['History', 'Military'],
  'The Timeless Way of Building': ['Design', 'Philosophy'],
  'The Weather Machine': ['Science', 'Technology'],
  'The Woman Who Smashed Codes': ['Biography', 'History', 'Military'],
  'The Woman in Me': ['Memoir'],
  'Their Eyes Were Watching God': ['Fiction'],
  'Thinking in Systems': ['Science', 'Philosophy'],
  'Thinking, Fast and Slow': ['Psychology', 'Science'],
  'Titan': ['Biography', 'Business', 'History'],
  "Turing's Cathedral": ['Technology', 'History', 'Science'],
  'Tuxedo Park': ['History', 'Science'],
  'User Friendly': ['Design', 'Technology'],
  'Valley of Genius': ['Technology', 'History', 'Business'],
  'We Were Eight Years in Power': ['Politics', 'History'],
  'What Happened': ['Politics', 'Memoir'],
  'What If?': ['Science'],
  'What Tech Calls Thinking': ['Technology', 'Philosophy'],
  'When We Cease to Understand the World': ['Fiction', 'Science'],
  "Why We're Polarized": ['Politics', 'Social Science'],
  'Wonderland': ['History', 'Technology', 'Science'],
  'Working': ['Memoir', 'Biography'],
  'Zero to One': ['Business', 'Technology'],
};
